### ISSUE TITLE
config.ini and stats.txt

### ISSUE THREAD

**Issue by guilhermemalfatti** [markoshorro/gem5ToMcPAT#1]
I have one commit in my local branch to add the these two files config.ini and stats.txt.

It will be good to others people when do the download, already have an example to run.

How can I do the merge in your repo? if you want of course.

**Comment by markoshorro** [comment]
Yes, it is a good idea. I do not know if you have seen the folder test, where I put these two files. However these are not updated. I guess what you are trying to do is a a 'pull request'.

**Comment by guilhermemalfatti** [comment]
done!!!

I did a pull request. Waiting the merge, because only you can merge pull requests.

Thanks
