### ISSUE TITLE
running script with Alpha FS

### ISSUE THREAD

**Issue by kien-tq** [markoshorro/gem5ToMcPAT#3]
Hi Marcos,
As discussed on the mailing list, I attach .ini  stats and the modified template here, there are some issues, 
1. Many basic values (i.e., same for any arch) were not set, e.g., total_cycles
2. From the provided template and example file, I observe that number of write access and read access for L2 are the same, but according to the stats file they must be different?

will report if I spot other issue. 
full log

> [config.ini]: finished parsing!
> [stats.txt]: finished parsing!
> Warning: simulation has not been done in detailed memory mode
> Thus there is a lack of stats and some values will be set to zero
> Parsing template...
> Warning: stat system 'total_cycles' may have not been set!
> Warning: stat system 'idle_cycles' may have not been set!
> Warning: stat system 'busy_cycles' may have not been set!
> Warning: param system.core0 'x86' may have not been set!
> Warning: param system.core0 'fetch_width' may have not been set!
> Warning: param system.core0 'decode_width' may have not been set!
> Warning: param system.core0 'issue_width' may have not been set!
> Warning: param system.core0 'peak_issue_width' may have not been set!
> Warning: param system.core0 'commit_width' may have not been set!
> Warning: some parameters missing to set properly 'pipeline_depth'!
> Warning: param system.core0 'instruction_buffer_size' may have not been set!
> Warning: param system.core0 'instruction_window_size' may have not been set!
> Warning: param system.core0 'fp_instruction_window_size' may have not been set!
> Warning: param system.core0 'ROB_size' may have not been set!
> Warning: param system.core0 'phy_Regs_IRF_size' may have not been set!
> Warning: param system.core0 'phy_Regs_FRF_size' may have not been set!
> Warning: param system.core0 'store_buffer_size' may have not been set!
> Warning: param system.core0 'load_buffer_size' may have not been set!
> Warning: param system.core0 'RAS_size' may have not been set!
> Warning: stat system.core0 'total_instructions' may have not been set!
> Warning: stat system.core0 'branch_instructions' may have not been set!
> Warning: stat system.core0 'branch_mispredictions' may have not been set!
> Warning: stat system.core0 'load_instructions' may have not been set!
> Warning: stat system.core0 'store_instructions' may have not been set!
> Warning: stat system.core0 'committed_int_instructions' may have not been set!
> Warning: stat system.core0 'committed_fp_instructions' may have not been set!
> Warning: stat system.core0 'pipeline_duty_cycle' may have not been set!
> Warning: stat system.core0 'total_cycles' may have not been set!
> Warning: stat system.core0 'idle_cycles' may have not been set!
> Warning: stat system.core0 'busy_cycles' may have not been set!
> Warning: stat system.core0 'ROB_reads' may have not been set!
> Warning: stat system.core0 'ROB_writes' may have not been set!
> Warning: stat system.core0 'rename_reads' may have not been set!
> Warning: stat system.core0 'rename_writes' may have not been set!
> Warning: stat system.core0 'fp_rename_reads' may have not been set!
> Warning: stat system.core0 'fp_rename_writes' may have not been set!
> Warning: stat system.core0 'inst_window_reads' may have not been set!
> Warning: stat system.core0 'inst_window_writes' may have not been set!
> Warning: stat system.core0 'inst_window_wakeup_accesses' may have not been set!
> Warning: stat system.core0 'fp_inst_window_reads' may have not been set!
> Warning: stat system.core0 'fp_inst_window_writes' may have not been set!
> Warning: stat system.core0 'fp_inst_window_wakeup_accesses' may have not been set!
> Warning: stat system.core0 'int_regfile_reads' may have not been set!
> Warning: stat system.core0 'int_regfile_writes' may have not been set!
> Warning: stat system.core0 'float_regfile_reads' may have not been set!
> Warning: stat system.core0 'function_calls' may have not been set!
> Warning: stat system.core0 'ialu_accesses' may have not been set!
> Warning: stat system.core0 'fpu_accesses' may have not been set!
> Warning: stat system.core0 'mul_accesses' may have not been set!
> Warning: stat system.core0 'cdb_alu_accesses' may have not been set!
> Warning: stat system.core0 'cdb_mul_accesses' may have not been set!
> Warning: stat system.core0 'cdb_fpu_accesses' may have not been set!
> param: load_predictor not found!
> param: global_predictor not found!
> param: predictor_chooser not found!
> Warning: param system.core0.itlb 'number_entries' may have not been set!
> Warning: stat system.core0.itlb 'total_accesses' may have not been set!
> Warning: stat system.core0.itlb 'total_misses' may have not been set!
> Warning: stat system.core0.icache 'read_accesses' may have not been set!
> Warning: stat system.core0.icache 'read_misses' may have not been set!
> Warning: stat system.core0.dtlb 'total_accesses' may have not been set!
> Warning: stat system.core0.dtlb 'total_misses' may have not been set!
> Warning: stat system.core0.dcache 'read_accesses' may have not been set!
> Warning: stat system.core0.dcache 'write_accesses' may have not been set!
> Warning: stat system.core0.dcache 'read_misses' may have not been set!
> Warning: stat system.core0.dcache 'write_misses' may have not been set!
> Warning: stat system.core0.BTB 'read_accesses' may have not been set!
> Warning: stat system.core0.BTB 'write_accesses' may have not been set!
> Warning: stat system.L20 'read_accesses' may have not been set!
> Warning: stat system.L20 'write_accesses' may have not been set!
> Warning: stat system.L20 'read_misses' may have not been set!
> Warning: stat system.L20 'write_misses' may have not been set!
> Warning: param system.mc 'block_size' may have not been set!
> Warning: param system.mc 'memory_channels_per_mc' may have not been set!
> Warning: param system.mc 'number_ranks' may have not been set!
> Warning: stat system.mc 'memory_accesses' may have not been set!
> Warning: stat system.mc 'memory_reads' may have not been set!
> Warning: stat system.mc 'memory_writes' may have not been set!
> finish filling!
> Parsing was successful!

---
## Thanks & regards, 

Kien

[stats.txt](https://github.com/markoshorro/gem5ToMcPAT/files/230941/stats.txt)
[stats.txt](https://github.com/markoshorro/gem5ToMcPAT/files/230942/stats.txt)
[m5out.zip](https://github.com/markoshorro/gem5ToMcPAT/files/230945/m5out.zip)

**Comment by markoshorro** [comment]
Okay, I think I have found the bug (basically the lexer was not finding anything due to a deadlock). I will try to fix it and then I will do a commit.
Thanks for reporting!

**Comment by markoshorro** [comment]
This fix should work for configuration file. I will keep working, so I will not close the issue yet
https://github.com/markoshorro/gem5ToMcPAT/commit/ff89c7ad9185a11541ed05dea1a8f8b6e0f380c8

**Comment by markoshorro** [comment]
About stats, there are some difference between names of values, so it will take time to catch them all... I made this parser thinking about X86 ISA, however I will try to adapt these params for any ISA.

**Comment by markoshorro** [comment]
I think it is really easy to implement new rules in the parser. It could be great your collaboration in order to match all the different names a value/param has in the different ISAs and make the parser more global.

**Comment by kien-tq** [comment]
Dear Marcos,

Thanks for your prompt response, I will look into the parser  code and try
with different ISA and report to you if I found some further issues.

**Comment by markoshorro** [comment]
Thanks! Nevertheless, I will keep working on the synonyms

**Comment by kien-tq** [comment]
Hi Marko,

I leave here the stats and config for X86, ARM, and ALPHA, obtained from FS simulation with O3 (detailed) cpus in case you need to test the tool.
Let me know if you have it fixed so I can give a try. thanks
[m5out_alpha.zip](https://github.com/markoshorro/gem5ToMcPAT/files/240244/m5out_alpha.zip)
[m5out_arm.zip](https://github.com/markoshorro/gem5ToMcPAT/files/240249/m5out_arm.zip)
[m5out_x86.zip](https://github.com/markoshorro/gem5ToMcPAT/files/240253/m5out_x86.zip)

**Comment by markoshorro** [comment]
Thanks for sharing those files. I have not worked yet too much on the synonyms, but I have put some default values in the params. This way McPAT should not ever fail, i.e., none of the params should be zero. Why did I do this? Because McPAT does not allow some params to be zero, and some CPU modes in gem5 have not such granularity, e.g. using timing CPU, there is not configuration for ALUs, and then the parser was setting the values to zero. Thus McPAT was complaining some values were zero, and then it was not working. I set some values in the parser to be the same as the template. This way the parser always give feasible values for McPAT, but maybe not 100% accurate. However it also depends on the CPU mode you are using. The more detailed, the more accurate!

But talking about ISAs, it is important to match the stats in all the ISAs. This is now my priority #1 in the TODO list. But it takes time, and mine is right now quite limited, due to some finals and my thesis. Hope to have time soon!

**Comment by YaguangL** [comment]
Hi Marcos,

**Comment by YaguangL** [comment]
Hi Marcos,
The same problem as mentioned above. 
Waiting for your update to the code. At the same time I will look into the code.

Liyg

**Comment by mihelog** [comment]
Same here, though I'm running X86 SE with 16 cores. Could be a version issue. The stats.txt file differs than the latest Gem5 version in that instead of "system.cpu" it appends the CPU's identifier. For example "system.cpu00" is the first CPU.

I'm not sure if that's the reason but the rules in parser.l that have to do with the CPU such as active cycles do not match. I'm trying to debug and I'll let you know if I figure this out. It's been while since I touched lex code :-)

**Comment by markoshorro** [comment]
Indeed if the name of the params or stats changes, the parser will not recognize those items, therefore there is a need to adapt the lexer in order to recognize those alias.

I wonder why they change the names on the stats...

**Comment by mihelog** [comment]
Good question!

It made me wonder though. If the parser does not expect a CPU ID, does i support more than one cores?

**Comment by markoshorro** [comment]
I am afraid it does not... Nevertheless I have not tried yet
Probably we should open a new issue for that

**Comment by RzyDS** [comment]
Hi Marko
Did you modify parser?

**Comment by markoshorro** [comment]
I have not tried with Alpha yet.
You could try to fork this project and make it work with this ISA as well.

**Comment by RzyDS** [comment]
I want to add some param into your project. Must I just add my desirable param into parser.l file? or I must change other files too?

**Comment by markoshorro** [comment]
Yes you should add your param into parser.l file, this way the program will detect what you want. However, it is also needed to modify parser.y by adding a new rule in order to tell the parser "do something" when detecting your param in parser.l, otherwise the program will crash since you do not have any rule for the new param. You can follow the flow of the program by examining first the parser.l and then the parser.y
Hope this information to let you work independently.

**Comment by RzyDS** [comment]
Thank you so much for answering.

**Comment by jrswain85** [comment]
Hello markoshorro
I  ran  out.xml in McPAT and it returns the following Error 
 
number_of_cores/number_of_L2s/number_of_L3s/number_of_NoCs is/are not
correct!"*

Can you suggest a solution to it

**Comment by YaguangL** [comment]
Hi,

As it is suggestted that there is a error, which exists in the error of the number of some blocks.
You should correct the configuration of a CPU in the out.xml file.
I get the configuration of a CPU from gem5 simulator, then transform the configuration to out.xml file. How about you?

Yaguang Li


________________________________
发件人: jrswain85 [notifications@github.com]
发送时间: 2018年1月19日 17:32
收件人: markoshorro/gem5McPATparse
抄送: 李亚光; Comment
主题: Re: [markoshorro/gem5McPATparse] running script with Alpha FS (#3)


Hello markoshorro
I ran out.xml in McPAT and it returns the following Error

number_of_cores/number_of_L2s/number_of_L3s/number_of_NoCs is/are not
correct!"*

Can you suggest a solution to it

―

**Comment by markoshorro** [comment]
gem5 is dropping Alpha support, so this no longer makes sense
